### ISSUE TITLE
update box of health icon

### ISSUE THREAD

**Issue by Adam-** [severikupari1/strongholdofsecurity#2]
The game update today updated the box of health to remove the red cross icon, which is a restricted symbol in some jurisdictions. Consider updating the plugin icon to match the new one.

**Comment by severikupari1** [comment]
Hello, thanks for notifying! Could you provide me the link for the update and the image that I should use?

**Comment by Adam-** [comment]
It is available from the wiki https://oldschool.runescape.wiki/w/Box_of_Health

**Comment by severikupari1** [comment]
https://github.com/runelite/plugin-hub/pull/4888

Opened pr to plugin hub with updated icon.
